In [ ]:
pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.3 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset
import numpy as np

# Load the dataset from Hugging Face
dataset = load_dataset("sst")
dataset.column_names

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/load.py:1461: FutureWarning: The repository for sst contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/sst
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Generating train split:   0%|          | 0/8544 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1101 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2210 [00:00<?, ? examples/s]

{'train': ['sentence', 'label', 'tokens', 'tree'],
 'validation': ['sentence', 'label', 'tokens', 'tree'],
 'test': ['sentence', 'label', 'tokens', 'tree']}

In [ ]:
import pandas as pd

train_df = pd.DataFrame(dataset["train"])
test_df = pd.DataFrame(dataset["test"])

# Save the train and test DataFrames to CSV files
train_df.to_csv("dataset.csv", index=False)
test_df.to_csv("test_dataset.csv", index=False)
# Assuming 'dataset' is a dictionary containing 'train' and 'test' keys, each containing the respective datasets
train_sentences = dataset["train"]["sentence"]
train_labels = dataset["train"]["label"]
test_sentences = dataset["test"]["sentence"]
test_labels = dataset["test"]["label"]

# Display the first few elements of each list
print("Train Sentences:", train_sentences[:5])
print("Train Labels:", train_labels[:5])
print("Test Sentences:", test_sentences[:5])
print("Test Labels:", test_labels[:5])


Train Sentences: ["The Rock is destined to be the 21st Century 's new `` Conan '' and that he 's going to make a splash even greater than Arnold Schwarzenegger , Jean-Claud Van Damme or Steven Segal .", "The gorgeously elaborate continuation of `` The Lord of the Rings '' trilogy is so huge that a column of words can not adequately describe co-writer\\/director Peter Jackson 's expanded vision of J.R.R. Tolkien 's Middle-earth .", 'Singer\\/composer Bryan Adams contributes a slew of songs -- a few potential hits , a few more simply intrusive to the story -- but the whole package certainly captures the intended , er , spirit of the piece .', "You 'd think by now America would have had enough of plucky British eccentrics with hearts of gold .", 'Yet the act is still charming here .']
Train Labels: [0.6944400072097778, 0.833329975605011, 0.625, 0.5, 0.7222200036048889]
Test Sentences: ['Effective but too-tepid biopic', 'If you sometimes like to go to the movies to have fun , Wasabi is a g

In [ ]:
def map_sentiment_score(score):
    if score <= 0.2:
        return 0  # Very negative
    elif score <= 0.4:
        return 1  # Negative
    elif score <= 0.6:
        return 2  # Neutral
    elif score <= 0.8:
        return 3  # Positive
    else:
        return 4  # Very positive
# Preprocess the dataset
def preprocess_data(sentences, labels):
    preprocessed_sentences = []
    preprocessed_labels = []
    for sentence, score in zip(sentences, labels):
        sentiment_class = map_sentiment_score(score)
        preprocessed_sentences.append(sentence)
        preprocessed_labels.append(sentiment_class) # Fixed the typo here
    return preprocessed_sentences, preprocessed_labels
preprocessed_train_sentences, preprocessed_train_labels = preprocess_data(train_sentences, train_labels)
preprocessed_test_sentences, preprocessed_test_labels = preprocess_data(test_sentences, test_labels)


In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
df = pd.read_csv("dataset.csv")
df


sentence    label  \
0     The Rock is destined to be the 21st Century 's...  0.69444   
1     The gorgeously elaborate continuation of `` Th...  0.83333   
2     Singer\/composer Bryan Adams contributes a sle...  0.62500   
3     You 'd think by now America would have had eno...  0.50000   
4                  Yet the act is still charming here .  0.72222   
...                                                 ...      ...   
8539                                    A real snooze .  0.11111   
8540                                     No surprises .  0.22222   
8541  We 've seen the hippie-turned-yuppie plot befo...  0.75000   
8542  Her fans walked out muttering words like `` ho...  0.13889   
8543                                In this case zero .  0.34722   

                                                 tokens  \
0     The|Rock|is|destined|to|be|the|21st|Century|'s...   
1     The|gorgeously|elaborate|continuation|of|``|Th...   
2     Singer\/composer|Bryan|Adams|contributes|a|sle...   
3     You|'d|think|by|now|America|would|have|had|eno...   
4                  Yet|the|act|is|still|charming|here|.   
...                                                 ...   
8539                                    A|real|snooze|.   
8540                                     No|surprises|.   
8541  We|'ve|seen|the|hippie-turned-yuppie|plot|befo...   
8542  Her|fans|walked|out|muttering|words|like|``|ho...   
8543                                In|this|case|zero|.   

                                                   tree  
0     70|70|68|67|63|62|61|60|58|58|57|56|56|64|65|5...  
1     71|70|69|69|67|67|66|64|63|62|62|61|61|58|57|5...  
2     72|71|71|70|68|68|67|67|66|63|62|62|60|60|58|5...  
3     36|35|34|33|33|32|30|29|27|26|25|24|23|23|22|2...  
4             15|13|13|10|9|9|11|12|10|11|12|14|14|15|0  
...                                                 ...  
8539                                      7|6|5|5|6|7|0  
8540                                          5|4|4|5|0  
8541  41|40|38|37|36|36|39|42|43|35|34|31|30|30|29|2...  
8542  62|62|55|55|53|53|52|51|50|49|48|47|47|57|58|5...  
8543                                  8|8|7|6|6|7|9|9|0  

[8544 rows x 4 columns]

In [ ]:


import numpy as np

def extract_bigrams(sentences):
    bigrams = set()
    for sentence in sentences:
        words = sentence.split()
        for i in range(len(words) - 1):
            bigram = ' '.join(words[i:i+2])
            bigrams.add(bigram)
    return list(bigrams)

def create_bigram_index(bigrams):
    bigram_index = {bigram: i for i, bigram in enumerate(bigrams)}
    return bigram_index

import numpy as np

def one_hot_encode_bigrams(sentences, bigrams):
    bigram_index = {bigram: i for i, bigram in enumerate(bigrams)}
    one_hot_encoded = np.zeros((len(sentences), len(bigrams)), dtype=int)
    for i, sentence in enumerate(sentences):
        words = sentence.split()
        for j in range(len(words) - 1):
            bigram = ' '.join(words[j:j+2])
            if bigram in bigram_index:
                index = bigram_index[bigram]
                one_hot_encoded[i, index] = 1
    return one_hot_encoded


# Extract bigrams from sentences
bigrams = extract_bigrams(preprocessed_train_sentences)

# One-hot encode bigrams in training sentences
X_train = one_hot_encode_bigrams(preprocessed_train_sentences, bigrams)

# One-hot encode bigrams in testing sentences
X_test = one_hot_encode_bigrams(preprocessed_test_sentences, bigrams)








In [ ]:
del bigrams
del df
del preprocessed_train_sentences
print(type(X_train))
print(type(X_test))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


"import numpy as np\nimport matplotlib.pyplot as plt\n\nclass MultiClassLogisticRegression:\n\n    def __init__(self, n_iter = 10, thres=1e-3):\n        self.n_iter = n_iter\n        self.thres = thres\n\n    def fit(self, X, y, batch_size=20, lr=0.08, rand_seed=4, verbose=False):\n        np.random.seed(rand_seed)\n        self.classes = np.unique(y)\n        self.class_labels = {c:i for i,c in enumerate(self.classes)}\n        X = self.add_bias(X)\n        y = self.one_hot(y)\n        self.loss = []\n        self.weights = np.zeros(shape=(len(self.classes),X.shape[1]))\n        self.fit_data(X, y, batch_size, lr, verbose)\n        return self\n\n    def fit_data(self, X, y, batch_size, lr, verbose):\n      num_samples = X.shape[0]\n      i = 0\n      while (not self.n_iter or i < self.n_iter):\n        print(i)\n        self.loss.append(self.cross_entropy(y, self.predict_(X)))\n        for start in range(0, num_samples, batch_size):\n            end = min(start + batch_size, num_samp

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

class MultiClassLogisticRegression:
    # ...
    def __init__(self, n_iter=10, thres=1e-3, lr=0.1):
        self.n_iter = n_iter
        self.thres = thres
        self.lr = lr
        self.weights = None

    # def add_bias(self, X):
    #   return np.insert(X, 0, 1, axis=1)

# Modify the fit method to add bias to X
    def fit(self, X, y, batch_size=16, rand_seed=4, verbose=False):
      np.random.seed(rand_seed)
      self.classes = np.unique(y)
      self.class_labels = {c: i for i, c in enumerate(self.classes)}
      X = self.add_bias(X)
      y = self.one_hot(y)
      self.loss = []
      self.weights = np.zeros(shape=(len(self.classes), X.shape[1]))
      self.fit_data(X, y, batch_size, verbose)
      return self

    def fit_data(self, X, y, batch_size, verbose):
        i = 0
        n_samples = X.shape[0]
        indices = np.arange(n_samples)
        while not self.n_iter or i < self.n_iter:
            print(i)
            self.loss.append(self.cross_entropy(y, self.predict_(X)))
            np.random.shuffle(indices)  # Shuffle indices
            for start_idx in range(0, n_samples, batch_size):
                batch_indices = indices[start_idx : start_idx + batch_size]
                X_batch, y_batch = X[batch_indices], y[batch_indices]
                error = y_batch - self.predict_(X_batch)
                update = self.lr * np.dot(error.T, X_batch)
                self.weights += update
            if np.abs(update).max() < self.thres:
                break
            if i % 1000 == 0 and verbose:
                print(f'Training Accuracy at {i} iterations is {self.evaluate_(X, y)}')
            i += 1

    def predict(self, X):
        return self.predict_(self.add_bias(X))

    def predict_(self, X):
        pre_vals = np.dot(X, self.weights.T).reshape(-1, len(self.classes))
        return self.softmax(pre_vals)

    def softmax(self, z):
        exp_vals = np.exp(z - np.max(z, axis=1, keepdims=True))
        return exp_vals / np.sum(exp_vals, axis=1, keepdims=True)

    def predict_classes(self, X):



        self.probs_ = self.predict(X)
        return np.vectorize(lambda c: self.classes[c])(np.argmax(self.probs_, axis=1))

    def add_bias(self, X):
        if self.weights is None:
            return np.insert(X, 0, 1, axis=1)
        elif X.shape[1] == self.weights.shape[1]:
            return X
        else:
            return np.insert(X, 0, 1, axis=1)

    def one_hot(self, y):
        return np.eye(len(self.classes))[np.vectorize(lambda c: self.class_labels[c])(y).reshape(-1)]

    def score(self, X, y):
        return np.mean(self.predict_classes(X) == y)

    def evaluate_(self, X, y):
        return np.mean(np.argmax(self.predict_(X), axis=1) == np.argmax(y, axis=1))

    def cross_entropy(self, y, probs):
        return -1 * np.mean(y * np.log(probs))


In [ ]:
# Map sentiment scores to classes
# print(preprocessed_train_sentences.shape)
# print(preprocessed_train_labels)


In [ ]:
# problem 1
# Creating an instance of the Multiclass Logistic Regression model
logreg = MultiClassLogisticRegression()
X_train_int32 = X_train.astype(np.float16)
# # Fitting the model on the training data
logreg.fit(X_train_int32, np.array(preprocessed_train_labels))



#problem 2: (how to preprocess the X_test??)

# Making predictions on the test data


0
1
2
3
4
5
6
7
8
9


0
1
2
3
4
5
6
7
8
9


In [ ]:
X_test_with_bias = logreg.add_bias(X_test[:, :87249].astype(np.float16))


In [ ]:
predicted_labels = logreg.predict_classes(X_test_with_bias)

In [ ]:
print(predicted_labels)

[1 3 1 ... 3 3 1]


In [ ]:
def confusion_matrix(y_true, y_pred, num_classes):
    # Initialize confusion matrix with zeros
    conf_matrix = np.zeros((num_classes, num_classes), dtype=int)

    # Fill the confusion matrix
    for true_label, pred_label in zip(y_true, y_pred):
        conf_matrix[true_label][pred_label] += 1

    return conf_matrix

In [ ]:
def generate_confusion_matrix(true_labels, predicted_labels, num_classes):
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)
    for true_label, predicted_label in zip(true_labels, predicted_labels):
        true_label = int(true_label[0]) if isinstance(true_label, np.ndarray) else int(true_label)
        predicted_label = int(predicted_label[0]) if isinstance(predicted_label, np.ndarray) else int(predicted_label)
        confusion_matrix[true_label][predicted_label] += 1
    return confusion_matrix

def compute_precision_recall_f1(confusion_matrix):
    num_classes = len(confusion_matrix)
    precision = np.zeros(num_classes)
    recall = np.zeros(num_classes)
    f1_score = np.zeros(num_classes)
    for i in range(num_classes):
        true_positive = confusion_matrix[i][i]
        false_positive = sum(confusion_matrix[:, i]) - true_positive
        false_negative = sum(confusion_matrix[i, :]) - true_positive
        precision[i] = true_positive / (true_positive + false_positive) if true_positive + false_positive > 0 else 0
        recall[i] = true_positive / (true_positive + false_negative) if true_positive + false_negative > 0 else 0
        f1_score[i] = 2 * precision[i] * recall[i] / (precision[i] + recall[i]) if precision[i] + recall[i] > 0 else 0
    return precision, recall, f1_score

def macro_averaged_precision_recall_f1(precision, recall, f1_score):
    macro_precision = np.mean(precision)
    macro_recall = np.mean(recall)
    macro_f1_score = np.mean(f1_score)
    return macro_precision, macro_recall, macro_f1_score

In [ ]:
confusion_matrix= generate_confusion_matrix(preprocessed_test_labels, predicted_labels,5)
print("Confusion Matrix:\n", confusion_matrix)

precision, recall, f1_score=compute_precision_recall_f1(confusion_matrix)
macro_precision, macro_recall, macro_f1_score=macro_averaged_precision_recall_f1(precision, recall, f1_score)
print("macro_f1_score:", macro_f1_score)
print(" macro_recall:", macro_recall)
print("macro_precision:",  macro_precision)
print("f1_score:",  f1_score)

Confusion Matrix:
 [[ 40 137  35  50  17]
 [ 49 290 118 151  25]
 [ 18 152  63 135  21]
 [  7 103  75 256  69]
 [  8  61  41 171 118]]
macro_f1_score: 0.31232120973039174
 macro_recall: 0.3122317793595565
macro_precision: 0.3430910275548193
f1_score: [0.19950125 0.42151163 0.17475728 0.40219953 0.36363636]


In [ ]:
del precision
del macro_precision
del macro_recall
del macro_f1_score

In [ ]:
# num_classes = len(np.unique(preprocessed_test_labels))
# conf_matrix = confusion_matrix(preprocessed_test_labels, predicted_labels, num_classes)
# print("Confusion Matrix:")
# print(conf_matrix)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Create and train the model
logreg_sklearn = LogisticRegression(max_iter=1000)
logreg_sklearn.fit(X_train_int32, preprocessed_train_labels)


# # Predicting the classes
X_test_without_bias = X_test_with_bias[:, 1:]
predicted_labels_sklearn = logreg_sklearn.predict(X_test_without_bias)

# Computing the confusion matrix
conf_matrix_sklearn = confusion_matrix(preprocessed_test_labels, predicted_labels_sklearn)
print("Confusion Matrix (sklearn):")
print(conf_matrix_sklearn)



Confusion Matrix (sklearn):
[[ 33 142  33  58  13]
 [ 24 322 106 166  15]
 [ 11 160  62 143  13]
 [  7 108  70 276  49]
 [  6  73  42 188  90]]


In [ ]:
#metrics for logistic regression
num_classes = 5
confusion_matrix = generate_confusion_matrix(preprocessed_test_labels, predicted_labels_sklearn, num_classes)
print("Confusion Matrix:\n", confusion_matrix)

precision, recall, f1_score = compute_precision_recall_f1(confusion_matrix)
macro_precision, macro_recall, macro_f1_score = macro_averaged_precision_recall_f1(precision, recall, f1_score)
print("macro_f1_score:", macro_f1_score)
print("macro_recall:", macro_recall)
print("macro_precision:", macro_precision)
print("f1_score:", f1_score)

Confusion Matrix:
 [[ 33 142  33  58  13]
 [ 24 322 106 166  15]
 [ 11 160  62 143  13]
 [  7 108  70 276  49]
 [  6  73  42 188  90]]
macro_f1_score: 0.30606593534026333
macro_recall: 0.31061835344889355
macro_precision: 0.3675240876797952
f1_score: [0.18333333 0.44784423 0.17663818 0.41163311 0.31088083]


In [ ]:
accuracy = np.trace(confusion_matrix) / np.sum(confusion_matrix)
print("Accuracy:", accuracy)

Accuracy: 0.35429864253393667


In [ ]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix

# Create and train the model
sgd_logreg = SGDClassifier(loss='log', max_iter=1000, tol=1e-3)
sgd_logreg.fit(X_train_int32, preprocessed_train_labels)

# Predicting the classes


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


SGDClassifier(loss='log')

In [ ]:
predicted_labels_sgd = sgd_logreg.predict(X_test_without_bias)

# Computing the confusion matrix
conf_matrix_sgd = confusion_matrix(preprocessed_test_labels, predicted_labels_sgd)
print("Confusion Matrix (SGD):")
print(conf_matrix_sgd)

Confusion Matrix (SGD):
[[ 41 139  40  42  17]
 [ 37 331 129 115  21]
 [ 16 168  67 121  17]
 [ 11 118  94 228  59]
 [  7  69  56 156 111]]


In [ ]:
#metrics for SGD
conf_matrix_sgd = confusion_matrix(preprocessed_test_labels, predicted_labels_sgd)
print("Confusion Matrix (SGD):")
print(conf_matrix_sgd)

# Compute metrics
num_classes = 5
precision, recall, f1_score = compute_precision_recall_f1(conf_matrix_sgd)
macro_precision, macro_recall, macro_f1_score = macro_averaged_precision_recall_f1(precision, recall, f1_score)
print("macro_f1_score:", macro_f1_score)
print("macro_recall:", macro_recall)
print("macro_precision:", macro_precision)
print("f1_score:", f1_score)
accuracy = np.trace(conf_matrix_sgd) / np.sum(conf_matrix_sgd)
print("Accuracy:", accuracy)

Confusion Matrix (SGD):
[[ 41 139  40  42  17]
 [ 37 331 129 115  21]
 [ 16 168  67 121  17]
 [ 11 118  94 228  59]
 [  7  69  56 156 111]]
macro_f1_score: 0.3163032528355497
macro_recall: 0.31347020283483035
macro_precision: 0.35572057775669846
f1_score: [0.20971867 0.45404664 0.17290323 0.3890785  0.35576923]
Accuracy: 0.35203619909502265
